#
#   General Site Settigns
#
author: Alberto Silva
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

#   Social Media
twitter_username: jekyllrb
github_username: jekyll

#
#   General Build Settings
#
#   Source
source: app

#   Destination
destination: _site

#   Highlighter
highlighter: pygments

#   Markdown
markdown: kramdown

#   Url
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://albertosilva.me/" # the base hostname & protocol for your site
