#
#   General
author: Alberto Silva
title: Jekyll Boilerplate
email: asilvadesigns@gmail.com

#
#   Build
baseurl: ""
source: "./app/"
permalink: pretty

#
#   Excludes
exclude:
    - LICENSE
    - README.md
    - node_modules
    - gulpfile.js
    - Gemfile
    - package.json

#
#   Includes
include:
    - assets
