#
#   General Site Settigns
#
author: Author
title: Your awesome title
email: author@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

#   Social Media
twitter_username: jekyllrb
github_username: jekyll

#
#   General Build Settings
#
#   Url
baseurl: "/jekyll-start"   # remote
#baseurl: ""                 # local
url: ""                     # the base hostname & protocol for your site
permalink: pretty

exclude:
    - LICENSE
    - README.md
    - gulpfile.js
    - node_modules
    - package.json

collections:
    projects:
        output: true

defaults:
    - scope:
        type: projects
      values:
        layout: project
